[date]
value="Thu Sep  3 02:07:18 PM UTC 2026"
[support]
email="dev@ulinkot.tech"
[image]
value="debian-alarm-*"
[machines]
I_CIRUNODE="0"
I_CINODE="0"
I_ARNODE="0"
I_NETNODE="0"
V_CIRUNODE="x86_64, 3.8Ghz x8, 42Gb"
V_CINODE="aarch64, 1.5Ghz x4, 2Gb"
V_ARNODE="aarch64, 2.2Ghz x2, 1.8Ghz x4, 4Gb"
V_NETNODE="aarch64, 2.0Ghz x4, 4Gb"
